---
role:
  env: # gem_home: $HOME/.gem/...
    GEM_HOME: "$(ruby -e 'print Gem.user_dir')"
  install: echo $GEM_HOME
  pkg:
    - name: ruby
      action: install
      os: ["!darwin"]
    - name: ruby # rbenv/rvm, ruby-build
      action: install
      os: ["darwin"]
      args: --with-openssl-dir="$(brew --prefix openssl)"
    # ruby`ruby -e 'puts RUBY_VERSION[/\d+\.\d+/]'`-dev # libgemplugin-ruby
    - name: ruby-dev # $(ruby -e 'puts RUBY_VERSION[/\\d+\\.\\d+/]')-dev
      # rubygems, libgemplugin-ruby
      os: ["debian"]
    # - name: rubygems
    #   os: ["cygwin"]
    # https://bundler.io/
    # Manage gems with pacman on arch: ruby-<gem>
    # https://wiki.archlinux.org/index.php/Ruby#Managing_RubyGems_using_pacman
    # https://github.com/anatol/quarry
    # - name: ruby-bundler # rubygems
    #   os: ["arch"]
  link:
    - .gemrc
  post_install:
    # - GEM_HOME=$HOME/.gem
    # - PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
    - ruby --version
    - gem --version
    # - TODO darwin: PATH="/usr/local/Cellar/ruby/2.5.1/bin:$PATH"
    # - gem update --bindir /usr/local/bin --system
    # - gem update --bindir /usr/local/bin
    # - command: gem install --bindir /usr/local/bin --quiet bundler
    #   os: ["!arch"]
